title: Find Anime
email: whdzera@gmail.com
description: >-
  find scene anime from any image
baseurl: "/findanime"
url: ""

include:
  - app

exclude:
  - spec
  - package.json
  - package-lock.json
  - README.md
  - Rakefile
  - vite.config.js
